Move common functions to a shared file
* common.sh is included on build time
* most functions are copied from makepkg

diff --git a/archrelease.in b/archrelease.in
--- a/archrelease.in
+++ b/archrelease.in
@@ -1,18 +1,16 @@
 #!/bin/bash
 
-abort() {
-	echo ${1:-'archrelease: Cancelled'}
-	exit 1
-}
+m4_include(lib/common.sh)
 
 if [[ -z $1 ]]; then
-	abort 'Usage: archrelease <repo>...'
+	echo 'Usage: archrelease <repo>...'
+	exit 1
 fi
 
 # TODO: validate repo is really repo-arch
 
 if [[ ! -f PKGBUILD ]]; then
-	abort 'archrelease: PKGBUILD not found'
+	die 'archrelease: PKGBUILD not found'
 fi
 
 trunk=${PWD##*/}
@@ -21,24 +19,24 @@ trunk=${PWD##*/}
 # such as 'gnome-unstable'
 IFS='/' read -r -d '' -a parts <<< "$PWD"
 if [[ "${parts[@]:(-2):1}" == "repos" ]]; then
-	abort 'archrelease: Should not be in repos dir (try from trunk/)'
+	die 'archrelease: Should not be in repos dir (try from trunk/)'
 fi
 unset parts
 
 if [[ $(svn status -q) ]]; then
-	abort 'archrelease: You have not committed your changes yet!'
+	die 'archrelease: You have not committed your changes yet!'
 fi
 
 pushd .. >/dev/null
 IFS=$'\n' read -r -d '' -a known_files < <(svn ls -r HEAD "$trunk")
 for file in "${known_files[@]}"; do
 	if [[ ${file:(-1)} = '/' ]]; then
-		abort "archrelease: subdirectories are not supported in package directories!"
+		die "archrelease: subdirectories are not supported in package directories!"
 	fi
 done
 
 for tag in "$@"; do
-	echo -n "copying ${trunk} to ${tag}..."
+	stat_busy "copying ${trunk} to ${tag}"
 
 	if [[ -d repos/$tag ]]; then
 		declare -a trash
@@ -55,12 +53,12 @@ for tag in "$@"; do
 	# copy all files at once from trunk to the subdirectory in repos/
 	svn copy -q -r HEAD ${known_files[@]/#/$trunk/} "repos/$tag/"
 
-	echo 'done'
+	stat_done
 done
 
-echo -n "releasing package..."
+stat_busy "releasing package"
 printf -v tag_list ", %s" "$@"; tag_list="${tag_list#, }"
 svn commit -q -m "archrelease: copy ${trunk} to $tag_list" || abort
-echo 'done'
+stat_done
 
 popd >/dev/null
diff --git a/commitpkg.in b/commitpkg.in
--- a/commitpkg.in
+++ b/commitpkg.in
@@ -1,40 +1,22 @@
 #!/bin/bash
 
-abort() {
-	echo ${1:-'Cancelled'}
-	exit 1
-}
+m4_include(lib/common.sh)
 
 getpkgfile() {
 	if [[ ${#} -ne 1 ]]; then
-		echo 'ERROR: No canonical package found!' >&2
-		exit 1
+		die 'ERROR: No canonical package found!'
 	elif [ ! -f "${1}" ]; then
-		echo "ERROR: Package ${1} not found!" >&2
-		exit 1
+		die "ERROR: Package ${1} not found!"
 	fi
 
 	echo ${1}
-}
-
-##
-#  usage : get_full_version( $epoch, $pkgver, $pkgrel )
-# return : full version spec, including epoch (if necessary), pkgver, pkgrel
-##
-get_full_version() {
-	if [[ $1 -eq 0 ]]; then
-		# zero epoch case, don't include it in version
-		echo $2-$3
-	else
-		echo $1:$2-$3
-	fi
 }
 
 # Source makepkg.conf; fail if it is not found
 if [ -r '/etc/makepkg.conf' ]; then
 	source '/etc/makepkg.conf'
 else
-	abort '/etc/makepkg.conf not found!'
+	die '/etc/makepkg.conf not found!'
 fi
 
 # Source user-specific makepkg.conf overrides
@@ -45,7 +27,7 @@ fi
 cmd=${0##*/}
 
 if [ ! -f PKGBUILD ]; then
-	abort 'No PKGBUILD file'
+	die 'No PKGBUILD file'
 fi
 
 . PKGBUILD
@@ -54,7 +36,7 @@ pkgbase=${pkgbase:-$pkgname}
 case "$cmd" in
 	commitpkg)
 		if [ $# -eq 0 ]; then
-			abort 'usage: commitpkg <reponame> [-l limit] [-a arch] [commit message]'
+			die 'usage: commitpkg <reponame> [-l limit] [-a arch] [commit message]'
 		fi
 		repo="$1"
 		shift
@@ -63,7 +45,7 @@ case "$cmd" in
 		repo="${cmd%pkg}"
 		;;
 	*)
-		abort 'usage: commitpkg <reponame> [-l limit] [-a arch] [commit message]'
+		die 'usage: commitpkg <reponame> [-l limit] [-a arch] [commit message]'
 		;;
 esac
 
@@ -74,13 +56,13 @@ case "$repo" in
 		server='aur.archlinux.org' ;;
 	*)
 		server='gerolde.archlinux.org'
-		echo "Non-standard repository $repo in use, defaulting to server $server" ;;
+		msg "Non-standard repository $repo in use, defaulting to server $server" ;;
 esac
 
 # check if all local source files are under version control
 for s in "${source[@]}"; do
 	if [[ $s != *://* ]] && ! svn status -v "$s" | grep -q '^[ AMRX~]'; then
-		abort "$s is not under version control"
+		die "$s is not under version control"
 	fi
 done
 
@@ -90,7 +72,7 @@ for i in 'changelog' 'install'; do
 		# evaluate any bash variables used
 		eval file=\"$(sed 's/^\(['\''"]\)\(.*\)\1$/\2/' <<< "$file")\"
 		if ! svn status -v "${file}" | grep -q '^[ AMRX~]'; then
-			abort "${file} is not under version control"
+			die "${file} is not under version control"
 		fi
 	done < <(sed -n "s/^[[:space:]]*$i=//p" PKGBUILD)
 done
@@ -101,20 +83,19 @@ while getopts ':l:a:' flag; do
 	case $flag in
 		l) rsyncopts+=("--bwlimit=$2") ;;
 		a) commit_arch=$2 ;;
-		:) echo "option requires an argument -- '$OPTARG'" >&2
-			exit 1 ;;
-		\?) echo "invalid option -- '$OPTARG'" >&2
-			exit 1 ;;
+		:) die "option requires an argument -- '$OPTARG'" ;;
+		\?) die "invalid option -- '$OPTARG'" ;;
 	esac
 done
 shift $(( OPTIND - 1 ))
 
 if [ -n "$(svn status -q)" ]; then
-	echo -n 'committing changes to trunk...'
-	msgtemplate="upgpkg: $pkgbase $(get_full_version ${epoch:-0} $pkgver $pkgrel)"$'\n\n'
 	if [ -n "$1" ]; then
-		svn commit -q -m "${msgtemplate}${1}" || abort
+		stat_busy 'committing changes to trunk'
+		svn commit -q -m "${msgtemplate}${1}" || die
+		stat_done
 	else
+		msgtemplate="upgpkg: $pkgbase $(get_full_version)"$'\n\n'
 		msgfile="$(mktemp)"
 		echo "$msgtemplate" > "$msgfile"
 		if [ -n "$SVN_EDITOR" ]; then
@@ -126,23 +107,24 @@ if [ -n "$(svn status -q)" ]; then
 		else
 			vi "$msgfile"
 		fi
-		[ -s "$msgfile" ] || abort
-		svn commit -q -F "$msgfile" || abort
+		[ -s "$msgfile" ] || die
+		stat_busy 'committing changes to trunk'
+		svn commit -q -F "$msgfile" || die
 		unlink "$msgfile"
+		stat_done
 	fi
-	echo 'done'
 fi
 
 declare -a uploads
 
 for _arch in ${arch[@]}; do
 	if [ -n "$commit_arch" ] && [ "${_arch}" != "$commit_arch" ]; then
-		echo "skipping ${_arch}"
+		warning "skipping ${_arch}"
 		continue
 	fi
 
 	for _pkgname in ${pkgname[@]}; do
-		fullver=$(get_full_version ${epoch:-0} $pkgver $pkgrel)
+		fullver=$(get_full_version $_pkgname)
 		pkgfile=$(getpkgfile "$_pkgname-$fullver-${_arch}".pkg.tar.?z 2>/dev/null)
 		pkgdestfile=$(getpkgfile "$PKGDEST/$_pkgname-$fullver-${_arch}".pkg.tar.?z 2>/dev/null)
 
@@ -151,58 +133,58 @@ for _arch in ${arch[@]}; do
 		elif [ -f "$pkgdestfile" ]; then
 			pkgfile="$pkgdestfile"
 		else
-			echo "skipping ${_arch}"
+			warning "skipping ${_arch}"
 			continue 2
 		fi
 		uploads+=("$pkgfile")
 
 		sigfile="${pkgfile}.sig"
 		if [[ $SIGNPKG == 'y' ]] && [ ! -f "${sigfile}" ]; then
-			echo "Signing package ${pkgfile}..."
+			msg "Signing package ${pkgfile}..."
 			if [[ -n $GPGKEY ]]; then
 				SIGNWITHKEY="-u ${GPGKEY}"
 			fi
-			gpg --detach-sign --use-agent ${SIGNWITHKEY} "${pkgfile}" || abort
+			gpg --detach-sign --use-agent ${SIGNWITHKEY} "${pkgfile}" || die
 		fi
 		if [ -f "${sigfile}" ]; then
 			if ! gpg --verify "$sigfile" >/dev/null 2>&1; then
-				abort "Signature ${pkgfile}.sig is incorrect!"
+				die "Signature ${pkgfile}.sig is incorrect!"
 			fi
 			uploads+=("$sigfile")
 		else
-			abort "Signature ${pkgfile}.sig was not found"
+			die "Signature ${pkgfile}.sig was not found"
 		fi
 	done
 done
 
 if [[ -n $commit_arch ]]; then
-	archrelease "$repo-$commit_arch" || abort
+	archrelease "$repo-$commit_arch" || die
 else
-	archrelease "${arch[@]/#/$repo-}" || abort
+	archrelease "${arch[@]/#/$repo-}" || die
 fi
 
 if [[ ${#uploads[*]} -gt 0 ]]; then
-	echo 'uploading all package and signature files'
-	rsync "${rsyncopts[@]}" "${uploads[@]}" "$server:staging/$repo/" || abort
+	msg 'uploading all package and signature files'
+	rsync "${rsyncopts[@]}" "${uploads[@]}" "$server:staging/$repo/" || die
 fi
 
 if [ "${arch[*]}" == 'any' ]; then
 	if [ -d ../repos/$repo-i686 -a -d ../repos/$repo-x86_64 ]; then
 		pushd ../repos/ >/dev/null
-		echo "removing $repo-i686 and $repo-x86_64..."
+		stat_busy "removing $repo-i686 and $repo-x86_64"
 		svn rm $repo-i686
 		svn rm $repo-x86_64
 		svn commit -q -m "removed $repo-i686 and $repo-x86_64 for $pkgname"
-		echo 'done'
+		stat_done
 		popd >/dev/null
 	fi
 else
 	if [ -d ../repos/$repo-any ]; then
 		pushd ../repos/ >/dev/null
-		echo "removing $repo-any..."
+		stat_busy "removing $repo-any"
 		svn rm $repo-any
 		svn commit -q -m "removed $repo-any for $pkgname"
-		echo 'done'
+		stat_done
 		popd >/dev/null
 	fi
 fi
diff --git a/mkarchroot.in b/mkarchroot.in
--- a/mkarchroot.in
+++ b/mkarchroot.in
@@ -8,6 +8,8 @@
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
 
+m4_include(lib/common.sh)
+
 FORCE='n'
 RUN=''
 NOCOPY='n'
@@ -28,7 +30,7 @@ usage() {
 	echo '    -n            Do not copy config files into the chroot'
 	echo '    -c <dir>      Set pacman cache. Default: /var/cache/pacman/pkg'
 	echo '    -h            This message'
-	exit $1
+	exit 1
 }
 
 while getopts 'r:ufnhC:M:c:' arg; do
@@ -41,29 +43,26 @@ while getopts 'r:ufnhC:M:c:' arg; do
 		n) NOCOPY='y' ;;
 		c) cache_dir="$OPTARG" ;;
 		h|?) usage 0 ;;
-		*) echo "invalid argument '${arg}'"; usage 1 ;;
+		*) error "invalid argument '${arg}'"; usage ;;
 	esac
 done
 
 if [ "$EUID" != '0' ]; then
-	echo 'error: this script must be run as root.'
-	exit 1
+	die 'this script must be run as root.'
 fi
 
 shift $(($OPTIND - 1))
 
 if [ "$RUN" = '' -a $# -lt 2 ]; then
-	echo 'you must specify a directory and one or more packages'
-	usage 1
+	die 'you must specify a directory and one or more packages'
 elif [ $# -lt 1 ]; then
-	echo 'you must specify a directory'
-	usage 1
+	die 'you must specify a directory'
 fi
 
 working_dir="$(readlink -f ${1})"
 shift 1
 
-[ "${working_dir}" = '' ] && echo 'error: please specify a working directory' && usage 1
+[ "${working_dir}" = '' ] && die 'please specify a working directory'
 
 if [ -z "$cache_dir" ]; then
 	cache_conf=${working_dir}/etc/pacman.conf
@@ -150,9 +149,9 @@ chroot_lock () {
 
 	# Lock the chroot. Take note of the FD number.
 	if ! flock -n 9; then
-		echo -n "locking chroot..."
+		stat_busy "locking chroot"
 		flock 9
-		echo "done"
+		stat_done
 	fi
 }
 # }}}
@@ -162,9 +161,7 @@ if [ "$RUN" != "" ]; then
 	# run chroot {{{
 	#Sanity check
 	if [ ! -f "${working_dir}/.arch-chroot" ]; then
-		echo "error: '${working_dir}' does not appear to be a Arch chroot"
-		echo '       please build the image using mkarchroot'
-		exit 1
+		die "'${working_dir}' does not appear to be a Arch chroot"
 	fi
 
 	chroot_lock
@@ -177,8 +174,7 @@ if [ "$RUN" != "" ]; then
 else
 	# {{{ build chroot
 	if [ -e "${working_dir}" -a "${FORCE}" = "n" ]; then
-		echo "error: working dir '${working_dir}' already exists - try using -f"
-		exit 1
+		die "working dir '${working_dir}' already exists - try using -f"
 	fi
 
 	if { type -P btrfs && btrfs subvolume create "${working_dir}"; } &>/dev/null; then
@@ -202,8 +198,7 @@ else
 			op="${op}f"
 		fi
 		if ! pacman ${op} ${pacargs} $@; then
-			echo 'error: failed to install all packages'
-			exit 1
+			die 'failed to install all packages'
 		fi
 	fi
 
