actually fixed the problem this time
git-svn-id: http://projects.xennet.org/archtools/devtools/trunk@142 630f3fb4-fbd1-0310-a574-b293cca3120f

diff --git a/checkpkg b/checkpkg
--- a/checkpkg
+++ b/checkpkg
@@ -16,7 +16,14 @@ if [ ! -f $pkgname-$pkgver-$pkgrel.pkg.tar.gz ]; then
 	exit 1
 fi
 
-pkgurl=`pacman -Sp --noconfirm $pkgname | rev | cut -d ' ' -f 1 | rev`
+tmp=`pacman -Sp --noconfirm $pkgname`
+
+if [ $? -ne 0 ]; then
+	echo "Couldn't download previous package."
+	exit 1
+fi
+
+pkgurl=`echo $tmp | rev | cut -d ' ' -f 1 | rev`
 
 oldpkg=`strip_url $pkgurl`
 
