Add simple function to sign packages
Set SIGNPKG to y in makepkg.conf to enable signing.

diff --git a/commitpkg b/commitpkg
--- a/commitpkg
+++ b/commitpkg
@@ -130,9 +130,16 @@ for _arch in ${arch[@]}; do
 		fi
 		uploads+=("$pkgfile")
 
+		if [[ $SIGNPKG == 'y' ]]; then
+			echo "Signing package ${pkgfile}..."
+			gpg --detach-sign --use-agent -u "${PACKAGER}" "${pkgfile}" || abort
+		fi
+
 		sigfile="${pkgfile}.sig"
 		if [ -f "${sigfile}" ]; then
 			uploads+=("$sigfile")
+		elif [[ $SIGNPKG == 'y' ]]; then
+			abort "Signature ${pkgfile}.sig was not found"
 		fi
 	done
 	archrelease $repo-${_arch} || abort
