added a little extra feature to not let you upload to current, extra, or unstable with a 't' in the release
git-svn-id: http://projects.xennet.org/archtools/devtools/trunk@169 630f3fb4-fbd1-0310-a574-b293cca3120f

diff --git a/extrapkg b/extrapkg
--- a/extrapkg
+++ b/extrapkg
@@ -32,9 +32,17 @@ if [ ! -f $pkgfile ]; then
 fi
 
 if [ "$cmd" == "extrapkg" ]; then
+	if echo $pkgrel | grep "t" > /dev/null 2>&1; then
+		echo "Package can't be uploaded to extra with a 't' in the release"
+		exit 1
+	fi
 	repo="extra"
 	tag="CURRENT"
 elif [ "$cmd" == "currentpkg" ]; then
+	if echo $pkgrel | grep "t" > /dev/null 2>&1; then
+		echo "Package can't be uploaded to current with a 't' in the release"
+		exit 1
+	fi
 	repo="current"
 	tag="CURRENT"
 elif [ "$cmd" == "testingpkg" ]; then
@@ -45,6 +53,10 @@ elif [ "$cmd" == "testingpkg" ]; then
 	repo="testing"
 	tag="TESTING"
 elif [ "$cmd" == "unstablepkg" ]; then
+	if echo $pkgrel | grep "t" > /dev/null 2>&1; then
+		echo "Package can't be uploaded to unstable with a 't' in the release"
+		exit 1
+	fi
 	repo="unstable"
 	tag="CURRENT"
 fi
