Improve makepkg config loading for checkpkg and extrapkg.
Now, checkpkg and extrapkg will fail if /etc/makepkg.conf doesn't exist, and will also try to load in personal user's settings in ~/.makepkg.conf

Signed-off-by: Travis Willard <travis@archlinux.org>
Signed-off-by: Aaron Griffin <aaronmgriffin@gmail.com>

diff --git a/extrapkg b/extrapkg
--- a/extrapkg
+++ b/extrapkg
@@ -1,6 +1,17 @@
 #!/bin/bash
 
-source /etc/makepkg.conf
+# Source makepkg.conf; fail if it is not found
+if [ -r "/etc/makepkg.conf" ]; then
+	source "/etc/makepkg.conf"
+else
+    echo "/etc/makepkg.conf not found!"
+    exit 1
+fi
+
+# Source user-specific makepkg.conf overrides
+if [ -r ~/.makepkg.conf ]; then
+	source ~/.makepkg.conf
+fi
 
 cmd=`basename $0`
 
